---
- name: "victoriametrics | Include vminsert deployment tasks"
  when:
    - "lookup('ansible.builtin.vars',
      'victoriametrics_service_settings_vminsert', default='')
      not in ['', [], '[]', None]"
  block:
    - name: "victoriametrics | Set fact for deployment task [vminsert]"
      ansible.builtin.set_fact:
        victoriametrics_service_deploy_name: 'vminsert'
    - name: "victoriametrics | Include deployment tasks [vminsert]"
      ansible.builtin.include_tasks:
        file: "deploy.d/deploy_vm.yml"
- name: "victoriametrics | Include vmselect deployment tasks"
  when:
    - "lookup('ansible.builtin.vars',
      'victoriametrics_service_settings_vmselect', default='')
      not in ['', [], '[]', None]"
  block:
    - name: "victoriametrics | Set fact for deployment task [vmselect]"
      ansible.builtin.set_fact:
        victoriametrics_service_deploy_name: 'vmselect'
    - name: "victoriametrics | Include deployment tasks [vmselect]"
      ansible.builtin.include_tasks:
        file: "deploy.d/deploy_vm.yml"
- name: "victoriametrics | Include vmstorage deployment tasks"
  when:
    - "lookup('ansible.builtin.vars',
      'victoriametrics_service_settings_vmstorage', default='')
      not in ['', [], '[]', None]"
  block:
    - name: "victoriametrics | Set fact for deployment task [vmstorage]"
      ansible.builtin.set_fact:
        victoriametrics_service_deploy_name: 'vmstorage'
    - name: "victoriametrics | Include deployment tasks [vmstorage]"
      ansible.builtin.include_tasks:
        file: "deploy.d/deploy_vm.yml"
- name: "victoriametrics | Include vmauth deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_vmauth.yml"
  when:
    - "lookup('ansible.builtin.vars',
      'victoriametrics_service_settings_vmauth', default='')
      not in ['', [], '[]', None]"
