---
- name: "victoriametrics | Set fact for JMESPath query"
  ansible.builtin.set_fact:
    victoriametrics_service_enable_query: "{{ \"[].enable[] | map(&\" +
      lookup('ansible.builtin.vars', 'victoriametrics_service_deploy_name') +
      \" || 'false', @) | [0]\" }}"
- name: "{{ 'victoriametrics | Deploy ' + lookup('ansible.builtin.vars',
    'victoriametrics_service_deploy_name') + ' configuration' }}"
  ansible.builtin.template:
    src: "{{ lookup('ansible.builtin.vars',
      'victoriametrics_service_deploy_name') + '.j2' }}"
    dest: "{{ lookup('ansible.builtin.vars', 'victoriametrics_options_dest') +
      '/' + lookup('ansible.builtin.vars',
      'victoriametrics_service_deploy_name') }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "{{ 'Restart ' + lookup('ansible.builtin.vars',
      'victoriametrics_service_deploy_name') }}"
- name: "{{ 'victoriametrics | Enable ' + lookup('ansible.builtin.vars',
    'victoriametrics_service_deploy_name') + ' service' }}"
  ansible.builtin.systemd:
    name: "{{ lookup('ansible.builtin.vars',
      'victoriametrics_service_deploy_name') }}"
    enabled: "yes"
  when:
    - "lookup('ansible.builtin.vars', 'victoriametrics') |
       community.general.json_query(lookup('ansible.builtin.vars',
       'victoriametrics_service_enable_query', default='')) == 'true'"
